name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger on any tag starting with "v"

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact: target/release/rustguard-linux
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact: target/release/rustguard-macos
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: target/release/rustguard-windows.exe
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libxcb1-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Build
        run: cargo build --release

      # Rename the binary so each OS produces a unique filename.
      - name: Rename binary for Linux/macOS
        if: runner.os != 'Windows'
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then
            mv target/release/rustguard target/release/rustguard-linux
          elif [ "$RUNNER_OS" = "macOS" ]; then
            mv target/release/rustguard target/release/rustguard-macos
          fi
        shell: bash

      - name: Rename binary for Windows
        if: runner.os == 'Windows'
        run: |
          Rename-Item -Path "target\release\rustguard.exe" -NewName "rustguard-windows.exe"
        shell: pwsh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustguard-${{ matrix.os }}
          path: ${{ matrix.artifact }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List artifacts (debugging)
        run: ls -R artifacts

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/rustguard-ubuntu-latest/rustguard-linux
            artifacts/rustguard-macos-latest/rustguard-macos
            artifacts/rustguard-windows-latest/rustguard-windows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
